"""Sip-test: project per-agency total bytes by sampling N records.

Reads the existing manifest only — does not re-hit upstream.
"""

from __future__ import annotations

import math
import random
import statistics
from pathlib import Path

from uap_archive import config
from uap_archive.manifest import iter_manifest


def _project(samples: list[int], population: int) -> dict[str, float | int]:
    if not samples:
        return {"sampled": 0, "mean_size": 0, "projected_total": 0, "ci95_half_width": 0}
    mean = statistics.fmean(samples)
    if len(samples) > 1:
        stdev = statistics.stdev(samples)
        # 95% CI half-width on the total: 1.96 * stdev * N / sqrt(n)
        ci_half = 1.96 * stdev * population / math.sqrt(len(samples))
    else:
        ci_half = 0.0
    return {
        "sampled": len(samples),
        "mean_size": int(mean),
        "projected_total": int(mean * population),
        "ci95_half_width": int(ci_half),
    }


def siptest_agency(agency: str, sample: int = 20, seed: int = 0) -> dict:
    path = config.BY_AGENCY_DIR / f"{agency.lower()}.jsonl"
    objs = list(iter_manifest(path))
    sized = [o.size_bytes for o in objs if o.size_bytes]
    rng = random.Random(seed)
    chosen = rng.sample(sized, min(sample, len(sized))) if sized else []
    summary = _project(chosen, len(objs))
    summary.update({
        "agency": agency.upper(),
        "object_count": len(objs),
        "with_size": len(sized),
    })
    return summary


def write_projection_md(rows: list[dict], path: Path) -> None:
    lines = [
        "# Per-agency size projection",
        "",
        "Generated by `python -m uap_archive siptest`. Numbers are projections from",
        "a uniform random sample of records that have known `size_bytes`.",
        "",
        "| agency | objects | sized | sampled | mean size | projected total | ±95% |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        lines.append("| {agency} | {object_count} | {with_size} | {sampled} | "
                     "{mean_h} | {total_h} | ±{ci_h} |".format(
                         **r,
                         mean_h=_human(r["mean_size"]),
                         total_h=_human(r["projected_total"]),
                         ci_h=_human(r["ci95_half_width"]),
                     ))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _human(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    units = ["KB", "MB", "GB", "TB"]
    val = float(n)
    for u in units:
        val /= 1024
        if val < 1024:
            return f"{val:.1f} {u}"
    return f"{val:.1f} PB"


def run_all() -> Path:
    """Run siptest across every per-agency manifest, write size-projection.md."""
    rows = []
    for p in sorted(config.BY_AGENCY_DIR.glob("*.jsonl")):
        rows.append(siptest_agency(p.stem))
    out = config.MANIFESTS_DIR / "size-projection.md"
    write_projection_md(rows, out)
    return out
